In [1]:
import pandas as pd
import MLUtilites as ML
import numpy as np
import seaborn as sns

df = pd.read_csv("https://raw.githubusercontent.com/OmarGard/Bedu-E2-Modulo5/main/Data/cleanData.csv")

In [2]:
data = np.array([9,2,8,4,5,6,7,8,29,15,11,12])
y = np.array([1,2,3,4,8,5,10,8,9,10,11,12])

In [3]:
[x_train, x_val, x_test, y_train, y_val, y_test]= ML.train_validation_test(data,y,0.7,0.2,0.1)
print(x_train)
print(y_train)
print(x_test)
print(y_test)
print(x_val)
print(y_val)

[29  2  9 12  7  6  8  5]
[ 9  2  1 12 10  5  8  8]
[15  8]
[10  3]
[11  4]
[11  4]


In [4]:
train, test = ML.separation_k_fold(data,2,True)
# train

Ciclo: 1
	 datos para entrenamiento:[ 2  4  5  7 15 11]
	 datos para prueba:[ 9  8  6  8 29 12]
Ciclo: 2
	 datos para entrenamiento:[ 9  8  6  8 29 12]
	 datos para prueba:[ 2  4  5  7 15 11]


/home/alan/.local/lib/python3.8/site-packages/sklearn/utils/validation.py:70: FutureWarning: Pass shuffle=True as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [5]:
y_esperados = np.array([1,1,0,1,1,1,0,0,0,1,1,0])
y_predichos = np.array([0,0,0,1,1,0,1,0,1,0,1,1])
y_esperados2 = np.array([1,1,1,1,0,1,1,0,0,1,1,0])
y_predichos2 = np.array([1,0,1,0,1,0,0,0,1,0,0,1])

In [6]:
TN, FP, FN, TP = ML.matrix_confusion(y_predichos,y_esperados, printed=True)

matriz de confusión 
[[2 4]
 [3 3]]


In [7]:
accuracy, sensitivity, specificity = ML.results_matrix_confusion(TN, FP, FN, TP, printed=True)

precisión: 41.667
sensibilidad: 50.000
specificidad: 33.333


In [8]:
ML.clasification_comparative(y_esperados,y_predichos,y_esperados2,y_predichos2)

Clasificador 1 es mejor que clasificador 2 en cuanto a precisión: 41.667 > 25.000
Clasificador 1 es mejor que clasificador 2 en cuanto a sensibilidad: 42.857 > 25.000
Clasificador 1 es mejor que clasificador 2 en cuanto a especificidad: 40.0 > 25.000


In [9]:
X = df[["CO2","CH4","N2O"]][:100]
y = df["total_respiratory_diseases"][:100]
r = ML.multiclass_test(X,y,"OneVsRest")
r


/home/alan/.local/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/home/alan/.local/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/home/alan/.local/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/home/alan/.local/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "
/home/alan/.local/lib/python3.8/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the numbe

array([  653,   653, 10185, 10185,   653,   182,   653,   653,   653,
         653,   182,   653,   653,   653,   653,   653,   653,   653,
         653,   653,  3909,  3909, 10185,   653,   653,   653,   653,
         653,  3909,   653,  3909,   653,   653, 10185,   653, 10185,
         653,  3909,   653,   653,   653,   653,   653,  3909,  3909,
         653,   653,   653,   653, 10185,  3909,   653,   653,   653,
        3909,   653,   653,   653,   653,   653,   653,   653,   653,
         182,   653,   653,   653,   653,   653, 10185,   653,   653,
         653,   653,   653,   653,   653,  3909,   653, 10185,  3909,
         653,   653,   653,   653,   653,   653,   653, 10185,   653,
        3909,   653,  3909,   653,   182,   653, 10185,   653,   653,
         653])